### ISSUE TITLE
high cpu ram usage

### ISSUE THREAD

**Issue by fakhamatia** [pranaygp/vscode-css-peek#62]
When i enable this extension RAM and CPU go to 100% 
This problem only in Linux in Windows its OK
Any body knows alternative this ?

**Comment by JonKrone** [comment]
Ditto, I'm having high CPU usage on load of a new folder.

**Comment by CaffeinatedCM** [comment]
I opened a new folder and my CPU usage went to 100%. I used VS Codes process explorer and saw that this extension was causing it. 

I'm on Windows 10

**Comment by pranaygp** [comment]
Make sure you're on version 3.0.2. It should help solve this problem for *some* instances.

**Comment by pranaygp** [comment]
This is resolved in CSS Peek 4.0.0

**Comment by Pra3t0r5** [comment]
This is still an issue on 4.2.0 with very large projects. 
I'm on Ubuntu 20.04 LTS.
